spring:
  ## Redis配置
  redis:
    password: 860079445
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最小空闲
        min-idle: 0
        #最大空闲
        max-idle: 8
    #连接超时时间
    timeout: 10000
    host: localhost
  ##Redisson配置
  redisson:
    config-file:
      yaml: classpath:redisson.yml